version: '3.6'

services:

  # Backend API
  fire-fastpitch-api:
    build: ./
    command: npm start
    working_dir: /usr/src/fire-fastpitch-api
    environment:
      POSTGRES_URI: postgres://postgres:postgres@postgres:5432/fire-fastpitch-docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/fire-fastpitch-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fire-fastpitch-docker
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./fire.sql:/docker-entrypoint-initdb.d/fire.sql
    